name: Simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v5

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: 依存関係をインストール
        run: npm ci

      - name: ビルド（存在すれば）
        run: npm run build --if-present

      - name: テスト実行
        run: npm test
